targets:
  $default:
    sources:
      - "node/**"
      - "lib/**"
      - "test/**"
    builders:
      dirk_code_builder:
        enabled: True
      build_node_compilers|entrypoint:
        generate_for:
          - node/**
          - lib/**
        options:
          compiler: dart2js
          # List any dart2js specific args here, or omit it.
          dart2js_args:
            - --minify