targets:
  $default:
    sources:
      - "node/**"
      - "lib/**"
      - "test/**"
      - $packages$
    builders:
      node_preamble:
        generate_for:
          - node/**
          - lib/**
        options:
          compiler: dart2js
          # List any dart2js specific args here, or omit it.
          dart2js_args:
            - --minify