name: functions
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

analyzer:
  enable-experiment:
    - non-nullable

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  built_collection: ^5.0.0
  build: '>=0.10.0 <2.1.0'
  built_value:
  firebase_functions_interop: ^1.0.2
  node_interop: ^1.0.3
  js: ^0.6.1+1
  firebase_admin_interop: ^2.1.0
  bazel_worker: ^1.0.0-nullsafety.0
  fixnum: ^1.0.0-nullsafety
  protobuf: 0.41.2

  foundation:
    path: ../../foundation/

  uuid: ^3.0.2
  http_parser: '>=0.0.1 <4.0.0'





dev_dependencies:
  build_runner:
  pedantic: ^1.11.0
  test: ^1.16.8
  node_preamble: ^2.0.0
  web_socket_channel: ^2.0.0
  crypto: ^3.0.0
  built_value_generator: ^8.0.4
  cli_util: '>=0.1.2 <1.0.0'


dependency_overrides:
  built_value_generator:
  firebase_admin_interop: ^2.1.0
  crypto: ^3.0.0
  bazel_worker: ^1.0.0
  protobuf: ^2.0.0
  fixnum: ^1.0.0
  shelf_static: ^1.0.0
  http_parser: ^4.0.0
  node_preamble: ^1.4.0

