name: functions
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  firebase_functions_interop: ^1.0.2
  node_interop: ^1.0.3
  js: ^0.6.1+1
  firebase_admin_interop: ^2.1.0

  foundation:
    path: ../../foundation/

  uuid: ^2.2.2


dev_dependencies:

  build_runner: ^1.7.3
  build_node_compilers: ^0.2.0

dependency_overrides:
  firebase_admin_interop: ^2.1.0